footer:
  social:
    github:
      icon: '<img src="/images/github.png"/>'
      url: https://github.com/yutingzhao1991
    twitter:
      icon: '<img src="/images/twitter.png"/>'
      url: https://x.com/yudao1024
    wechat:
      icon: '<img src="/images/wechat.png"/>'
      url: /2021/è®¡åˆ’æä¸ªå…¬ä¼—å·æ¥ä¸€æœ¬æ­£ç»çš„èƒ¡è¯´ä¸€é€š/
    rss:
      icon: '<img src="/images/rss.png"/>'
      url: /atom.xml
open_graph:
  enable: true
  twitter_id: yudao1024
logo:
  subtitle: "å†™äº›æœ‰è¶£æ–‡ç« ï¼Œå°½æ˜¯ç‹—å±æš´è®ºã€‚ | ç”Ÿæ´»å’¸æ·¡é…¸è¾£ï¼Œæ·»ç¢—é…’é…¿å¹´ç³• ğŸ¥‚ã€‚" # 'æ–‡å­—1 | æ–‡å­—2' (é¼ æ ‡æ”¾ä¸Šå»ä¼šåˆ‡æ¢åˆ°æ–‡å­—2)
style:
  leftbar:
    background-image: "linear-gradient(0deg, #f5f5f5, #e0e0e0)"
    blur-px: 100px # æ¨¡ç³ŠåŠå¾„
    blur-bg: var(--alpha60) # æ¨¡ç³Šé¢œè‰²
